### PR TITLE
expand the game state update to include opponent data

### PR DESCRIPTION
**Pull request by kzfubar**
I would like to augment the capablities of the bot players, this first requires that the bots get access to more data about the game state.

to start, let's update the bot with the opponents played cards, and the opponents tableu data.

i believe that after each opponent's hand has been seen once, we should be able to track that hand as it moves across the table. however, i believe it will be best to wait until later to add that functionality in the name of a simpler preliminary change.

### CODE REVIEW

**Review by rocket3989 — DISMISSED** [review]
LGTM! be sure to run formatter and linter before commits

**Comment by rocket3989** [comment]
@kzfubar please open a new PR with a [signed commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification). Currently, merging to this repo is blocked for unsigned commits

**Comment by kzfubar** [comment]
i've, uh, hijacked this PR for signing the commit. 
history erased but possibly cleaner ?

**Review by rocket3989 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
